### PR TITLE
Upgrade the version of Chocolatey in strongbox-web-integration to the latest #1826

### LINKED ISSUE #1826: Upgrade the version of Chocolatey in strongbox-web-integration to the latest
# Task Description

As part of #1825 , we need to upgrade the version of Chocolatey in [strongbox-web-integration-tests] to the latest.

# Tasks

The following tasks will need to be carried out:
* [x] Update [ci-build-images] to use the latest version of Chocolatey for Linux.
* [x] Rebuild the images for Chocolatey.
* [x] Check if all the tests in the [strongbox-web-integration-tests] still pass.

# Task Relationships

This task:
* Is a sub-task of: #1825

# Useful Links

* [strongbox-web-integration-tests]
* [ci-build-images]

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @steve-todorov

[strongbox-web-integration-tests]: https://github.com/strongbox/strongbox-web-integration-tests/
[ci-build-images]: https://github.com/strongbox/ci-build-images

### PR DESCRIPTION
**Pull request by avinash28196**
# Pull Request Description

Upgrade the version of Chocolatey in strongbox-web-integration to the latest.

@steve-todorov I have Updated chocolatey version to the latest. If you want me to update it to the stable version let me know.

This pull request closes strongbox/strongbox#1826.

# Acceptance Test

* [x] Running `./build.sh` successfully builds all images.

# Questions

* Does this pull request somehow break backward compatibility? 
  * [ ] Yes, it will require fixing build jobs.
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by carlspring** [comment]
Hi!

Thank you for your contribution!

Would you mind signing the ICLA, as described in the [Contributing](https://github.com/strongbox/strongbox/blob/master/CONTRIBUTING.md) page?

Also, please, feel free to join our [chat channel](https://chat.carlspring.org/), if you'd like to learn more about the project and/or like to find out what else you could help with.

Kind regards,

Martin

**Comment by steve-todorov** [comment]
Hi, 

Thanks for your contribution!

If you run `docker run -it --rm strongboxci/alpine:jdk8-mvn3.6-mono5-nuget3.4-choco0.10-PR-17` you'll see an error:

```
Choco: log4net:ERROR Failed to initialize configuration file watcher for file [/opt/chocolatey/choco.exe.config]
System.InvalidOperationException: object_op ---> System.BadImageFormatException: Method has no body
  at System.IO.CoreFX.FileSystemWatcher.StartRaisingEvents () [0x0001c] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
  at System.IO.CoreFX.FileSystemWatcher.StartRaisingEventsIfNotDisposed () [0x00019] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
  at System.IO.CoreFX.FileSystemWatcher.set_EnableRaisingEvents (System.Boolean value) [0x0001d] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
  at (wrapper remoting-invoke-with-check) System.IO.CoreFX.FileSystemWatcher.set_EnableRaisingEvents(bool)
  at System.IO.CoreFXFileSystemWatcherProxy+<>c.<StartDispatching>b__9_0 (System.IO.CoreFX.FileSystemWatcher internal_fsw, System.IO.FileSystemWatcher fsw) [0x00048] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
  at System.IO.CoreFXFileSystemWatcherProxy.Operation (System.Action`4[T1,T2,T3,T4] map_op, System.Action`2[T1,T2] object_op, System.Object handle, System.Action`2[T1,T2] cancel_op) [0x00184] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
   --- End of inner exception stack trace ---
  at System.IO.CoreFXFileSystemWatcherProxy.Operation (System.Action`4[T1,T2,T3,T4] map_op, System.Action`2[T1,T2] object_op, System.Object handle, System.Action`2[T1,T2] cancel_op) [0x001a6] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
  at System.IO.CoreFXFileSystemWatcherProxy.StartDispatching (System.Object handle) [0x00004] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
  at System.IO.FileSystemWatcher.Start () [0x0001b] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
  at System.IO.FileSystemWatcher.set_EnableRaisingEvents (System.Boolean value) [0x0003d] in <91935ad653254a93b9d73a9f8f2f7a2d>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileSystemWatcher.set_EnableRaisingEvents(bool)
  at log4net.Config.XmlConfigurator+ConfigureAndWatchHandler..ctor (log4net.Repository.ILoggerRepository repository, System.IO.FileInfo configFile) [0x000bd] in <d08f57580d6b49efa6b59db67c9fe684>:0 
  at log4net.Config.XmlConfigurator.InternalConfigureAndWatch (log4net.Repository.ILoggerRepository repository, System.IO.FileInfo configFile) [0x000b9] in <d08f57580d6b49efa6b59db67c9fe684>:0 
```

Can you please check it out?

Other than that - LGTM. :)

**Comment by avinash28196** [comment]
@steve-todorov I'm working on it

**Comment by steve-todorov** [comment]
@avinash28196 ping - any updates? :)

**Comment by steve-todorov** [comment]
Thanks for your work but since there hasn't been any updates - I'm closing this PR in favor of #23 which also resolves the mentioned above issue.

**Pull request closed without merging**
