### PR TITLE
Updated the sbt version.

### PR DESCRIPTION
**Pull request by dotbg**
# Pull Request Description

This pull request refs. [strongbox #1830](https://github.com/strongbox/strongbox/issues/1830)

# Acceptance Test

* [x] Running `./build.sh` successfully builds all images.

# Questions

* Does this pull request somehow break backward compatibility? 
  * [ ] Yes, it will require fixing build jobs.
  * [x] No

* Does this pull request require other pull requests to be merged first? 
  * [ ] Yes, please see #...
  * [x] No

* Does this require an update of the documentation?
  * [ ] Yes, please see strongbox/strongbox-docs#{PR_NUMBER}
  * [x] No

### CODE REVIEW

**Comment by steve-todorov** [comment]
Hey,

This PR is closed and has a missing branch. However it is required for https://github.com/strongbox/strongbox-web-integration-tests/pull/67. Can you please create a new PR?

**Comment by dotbg** [comment]
I'll do a new one. 
It is not required for the tests, as this was the minor version bump

**Comment by steve-todorov** [comment]
Can you double check the strongbox/strongbox#1830 ?

> - [ ] Update ci-build-images to use the latest version of SBT for Linux.

This PR was actually necessary, because this repository contains the docker images we use down the pipeline. :) 
When you create the new PR, please make sure to include the `Use SBT_VERSION env var b5be991` commit since it fixes one of the build scripts for SBT. 

Thanks!

**Comment by steve-todorov** [comment]
I've made a PR and merged it already. Thanks for your help on this! :)

**Pull request closed without merging**
